Migrated to biomejs, reverted url delete, removed eslint comment.
wei/socialify pull request #290
Opened 2024-04-29 17:35 UTC by KemingHe

@wei 
Issue ref: fixed #271 
Rejected PR ref: fixed #286

2024-04-29 17:37 UTC, KemingHe commented
@wei By the way, would you consider a staging branch before production? The current setup is auto-deploy on `master`, which puts a lot of pressure on the reviewer, speaking from experience.

2024-04-30 01:22 UTC, wei requested changes
Overall LGTM, please review comments.

In addition, Chinese characters are no longer being rendered correctly.

Production: [![](https://socialify.git.ci/wei/socialify/image?description=1&descriptionEditable=%F0%9F%A4%96%20Chinese%EF%BC%9A%E4%B8%AD%E6%96%87%20%3C%3C%3C%20should%20display%20correctly&language=1&name=1&owner=1&stargazers=1&theme=Light)](https://socialify.git.ci/wei/socialify/image?description=1&descriptionEditable=%F0%9F%A4%96%20Chinese%EF%BC%9A%E4%B8%AD%E6%96%87%20%3C%3C%3C%20should%20display%20correctly&language=1&name=1&owner=1&stargazers=1&theme=Light)

This PR preview:
[![](https://socialify-git-fork-keminghe-master-github-socialify.vercel.app/wei/socialify/image?description=1&descriptionEditable=%F0%9F%A4%96%20Chinese%EF%BC%9A%E4%B8%AD%E6%96%87%20%3C%3C%3C%20should%20display%20correctly&language=1&name=1&owner=1&stargazers=1&theme=Light)](https://socialify-git-fork-keminghe-master-github-socialify.vercel.app/wei/socialify/image?description=1&descriptionEditable=%F0%9F%A4%96%20Chinese%EF%BC%9A%E4%B8%AD%E6%96%87%20%3C%3C%3C%20should%20display%20correctly&language=1&name=1&owner=1&stargazers=1&theme=Light)

I suspect `common/font.ts` changes is causing Chinese characters to have render issues. Could you take a look?

Since that file is pulled directly from an upstream source, can we ignore that file completely using biomejs, similar to eslint-ignore?

2024-04-30 01:22 UTC, wei commented on src/components/configuration/config.tsx
> +    urlParams._name = undefined
Still seeing this hmm, please undo.

2024-04-30 01:22 UTC, wei commented on biome.json
> +        "noDelete": "warn"
This is fine, just curious does biomejs have an inline ignore or do you have to set it globally in the config?

2024-04-30 01:24 UTC, wei commented
> @wei By the way, would you consider a staging branch before production? The current setup is auto-deploy on `master`, which puts a lot of pressure on the reviewer, speaking from experience.

Thanks for the suggestion. We are using Vercel for Pull Request previews which can act as staging. This is how I am able to test your changes live: https://socialify-git-fork-keminghe-master-github-socialify.vercel.app/

2024-04-30 04:02 UTC, KemingHe commented on src/components/configuration/config.tsx
> +    urlParams._name = undefined
My bad, I think I need to tweak my BiomeJS setup a bit to not have it automatically change it back after my manual reversion. I'll keep you posted.

2024-04-30 04:04 UTC, KemingHe commented on biome.json
> +        "noDelete": "warn"
I will further investigate the fine-grained control option and include it in the next request. Thank you for pointing this out.

2024-04-30 10:22 UTC, wei commented
@KemingHe no need to keep closing prs. you could just add commits to your branch which will update the pr automatically 😁

2024-05-02 19:43 UTC, KemingHe commented
Back to working on more polishing...

2024-05-05 16:00 UTC, KemingHe commented
> Overall LGTM, please review comments.
> 
> In addition, Chinese characters are no longer being rendered correctly.
> 
> Production: [![](https://camo.githubusercontent.com/337c564e3218311c02a461a1234654c64f43f655ab38abeba01d64f7ac67702e/68747470733a2f2f736f6369616c6966792e6769742e63692f7765692f736f6369616c6966792f696d6167653f6465736372697074696f6e3d31266465736372697074696f6e4564697461626c653d2546302539462541342539362532304368696e65736525454625424325394125453425423825414425453625393625383725323025334325334325334325323073686f756c64253230646973706c6179253230636f72726563746c79266c616e67756167653d31266e616d653d31266f776e65723d31267374617267617a6572733d31267468656d653d4c69676874)](https://socialify.git.ci/wei/socialify/image?description=1&descriptionEditable=%F0%9F%A4%96%20Chinese%EF%BC%9A%E4%B8%AD%E6%96%87%20%3C%3C%3C%20should%20display%20correctly&language=1&name=1&owner=1&stargazers=1&theme=Light)
> 
> This PR preview: [![](https://camo.githubusercontent.com/cf57156bad9f5ea2bc0a15025f2d852ab65e0e16a54edc65aba051b12d0ae862/68747470733a2f2f736f6369616c6966792d6769742d666f726b2d6b656d696e6768652d6d61737465722d6769746875622d736f6369616c6966792e76657263656c2e6170702f7765692f736f6369616c6966792f696d6167653f6465736372697074696f6e3d31266465736372697074696f6e4564697461626c653d2546302539462541342539362532304368696e65736525454625424325394125453425423825414425453625393625383725323025334325334325334325323073686f756c64253230646973706c6179253230636f72726563746c79266c616e67756167653d31266e616d653d31266f776e65723d31267374617267617a6572733d31267468656d653d4c69676874)](https://socialify-git-fork-keminghe-master-github-socialify.vercel.app/wei/socialify/image?description=1&descriptionEditable=%F0%9F%A4%96%20Chinese%EF%BC%9A%E4%B8%AD%E6%96%87%20%3C%3C%3C%20should%20display%20correctly&language=1&name=1&owner=1&stargazers=1&theme=Light)
> 
> I suspect `common/font.ts` changes is causing Chinese characters to have render issues. Could you take a look?
> 
> Since that file is pulled directly from an upstream source, can we ignore that file completely using biomejs, similar to eslint-ignore?

Hi @wei, I'm having difficulties recreating the language rendering bug you encountered, this is my result with the same preview, everything looks okay so far:

<img width="1348" alt="Screenshot 2024-05-05 at 11 53 32 AM" src="https://github.com/wei/socialify/assets/44534763/789e2ec4-bd2e-4800-b6c8-811dbb5b5510">

<img width="1348" alt="Screenshot 2024-05-05 at 11 58 54 AM" src="https://github.com/wei/socialify/assets/44534763/f41006b3-1f22-4570-ace6-500d41383b56">

URL: https://socialify-git-fork-keminghe-master-github-socialify.vercel.app/wei/socialify/image?_name=undefined&_owner=undefined&description=1&descriptionEditable=%F0%9F%A4%96%20Chinese%3A%20%E4%B8%AD%E6%96%87%20%20%3C%3C%3C%20should%20display%20correctly&language=1&name=1&owner=1&stargazers=1&theme=Light

Could you please provide more details on what could be the cause on your end? Much appreciated!

2024-05-05 16:05 UTC, KemingHe commented
> @wei @KemingHe Oh wait, I see, the preview works but the actual image rendering doesn't. Hmmm... Give me a sec.

And I also broke the download dropdown somehow, gotta fix that quick as well 😅

2024-05-05 16:08 UTC, KemingHe commented
@wei I should probably add `playwright` or `puppeteer` behavior testing to this, these usage bugs are so hard to find. 🤔

2024-05-05 16:11 UTC, KemingHe commented
Okay, after some initial testing, it's not the url issue, but some internal issue, will keep working on it.

2024-05-05 18:00 UTC, wei commented
> @wei I should probably add `playwright` or `puppeteer` behavior testing to this, these usage bugs are so hard to find. 🤔

Good idea, we should actually prioritize adding tests like the upstream repo using [__image_snapshots__](https://github.com/vercel/satori/tree/main/test/__image_snapshots__) to ensure the rendered image match snapshots with different parameters, Chinese characters, logos, emojis, etc. Afterwards an e2e test of the frontend will be nice too.

2024-05-05 18:04 UTC, wei commented
Ideally the migration to biomejs should only be coding style change and not change any functionality.

2024-05-06 13:20 UTC, KemingHe commented
I'm archiving my current migration and starting from scratch. Closing pull request since I'm changing fork.

2024-05-06 13:20 UTC, closed without merging