🚩 Upgrade to NextJS v15
wei/socialify pull request #375
Opened 2024-10-25 16:45 UTC by shubhamkhan

### Application NextJS Upgrade to v15
This pull request upgrades the Next.js framework from the previous version to v15.
Please review the changes, and let me know if you have any questions or feedback.

2024-10-25 19:33 UTC, wei requested changes
Please follow the full NextJS 15 upgrade guide which includes upgrading to React 19.

Please review all the framework features and make adjustments to the app as needed.

Please recommend future improvements that can be done after the initial upgrade to NextJS 15.

2024-10-26 02:38 UTC, shubhamkhan commented
Hi @wei, I have upgrade to React v19 with dependencies.

2024-10-26 04:36 UTC, wei requested changes
Could you comment on any new features or changes nextjs and react 19 brings that we should adopt or could benefit from in the project? Thank you!

btw also missing changeset file as seen in the first comment by changeset bot.

2024-10-26 04:36 UTC, wei commented on package.json
> +    "dev": "next dev --turbopack",
can you explain this change or link to the source?

2024-10-26 04:36 UTC, wei commented on package.json
> +  }
Please run linter before committing.

2024-10-26 08:00 UTC, shubhamkhan commented on package.json
> +    "dev": "next dev --turbopack",
Turbopack I have used for incremental bundler optimized for JavaScript and TypeScript in Next.js and faster local development

2024-10-26 18:53 UTC, shubhamkhan commented
Hi @wei,
- Added a changeset to document the updates.
- Ensured code consistency with linting and ran tests successfully.

2024-10-27 04:56 UTC, wei commented
Hello, thanks for the update, however, we're still missing these items from the last review:

> Please review all the framework features and make adjustments to the app as needed.
> 
> Please recommend future improvements that can be adopted for NextJS after the initial upgrade.
> 
> Could you comment on any new features or changes nextjs and react 19 brings that we should adopt or could benefit from in the project? Thank you!

Please click re-request review once these points have been addressed.

2024-10-27 04:58 UTC, wei commented on package.json
> +    "dev": "next dev --turbopack",
Thanks I see the blogpost at https://nextjs.org/blog/turbopack-for-development-stable is using `--turbo` but your change is `--turbopack`. Do you have documentation on the difference?

2024-10-29 04:00 UTC, wei requested changes
Please address previous outstanding comments. Thank you!

2024-10-30 01:19 UTC, wei commented on package.json
> +    "dev": "next dev --turbopack",
@shubhamkhan could you respond to my comment above?

2024-10-30 01:20 UTC, wei commented on package.json
> +  }
Hey @shubhamkhan  This is not yet resolved ^

2024-10-30 01:23 UTC, wei commented
Great! Please check outstanding comments above (I tagged you again in case you missed it)

Please list out all the changes you have implemented with source links so we can get them fully reviewed and approved. 

Thank you!

2024-10-30 01:26 UTC, wei commented on src/components/mainWrapper.tsx
> +    }
Any reason to no longer redirect when response is falsy?

2024-10-30 01:27 UTC, wei commented on src/components/toaster.tsx
> +          aria-atomic="true"
What are these for? Could you link me the sources?

2024-10-30 01:27 UTC, wei commented on pages/index.tsx
> +  )
Any reason for this change?

2024-10-30 01:28 UTC, wei commented on pages/api/graphql.ts
> +    cache: 'force-cache',
How does cache behave with POST requests? Could you help me understand? TY!

2024-10-30 02:49 UTC, shubhamkhan reviewed
Hi @wei, Can you review the updated code and validate, I run lint and test before commit. Thank You!

2024-10-30 02:49 UTC, shubhamkhan commented on package.json
> +  }
Sure, I will do.

2024-10-30 02:49 UTC, shubhamkhan commented on package.json
> +    "dev": "next dev --turbopack",
Hi @wei, the `--turbo` flag was initially used when Turbopack was in its experimental phase. Now,` --turbopack` is stable and recommended for activating Turbopack in Next.js.

Main article: [Turbopack for Development](https://nextjs.org/blog/turbopack-for-development-stable) -> [Turbo Engine](https://turbo.build/pack/docs/core-concepts#the-turbo-engine): Core Concepts -> Getting Started: [Turbo Documentation](https://turbo.build/pack/docs)

Thank you!

2024-10-30 02:49 UTC, shubhamkhan commented on pages/index.tsx
> +  )
For maintaining coding structure

2024-11-23 22:42 UTC, wei commented
👋  Hey hey @shubhamkhan thanks for all the help thus far. I have gone ahead and upgraded a ton of other dependencies in master. I'm just wondering if you'll have some time to carry this PR through the finish line 😄 

Just to summarize a few requested changes:

- [ ] Rebase / merge in upstream master branch to get the latest changes and resolve merge conflicts.
- [ ] Remove irrelevant dependency and code changes, keep this PR single purposed - Next.js 15 and React 19 upgrade only
- [ ] Double check the latest versions on npm registry and make sure we are using the latest
- [ ] Please review all the framework features and make adjustments to the app as needed
- [ ] Please provide a description of every change for review
- [ ] Run linter

Afterwards, if you have time, 

- [ ] Please recommend future improvements that can be adopted for NextJS after the initial upgrade.
- [ ] Could you comment on any new features or changes nextjs and react 19 brings that we should adopt or could benefit from in the project? 

Please let me know, completely fine if you don't currently have the bandwidth to tackle this, many thanks!

2024-11-24 17:10 UTC, wei requested changes
👋  Hey hey @shubhamkhan thanks for all the help thus far. I have gone ahead and upgraded a ton of other dependencies in master. I'm just wondering if you'll have some time to carry this PR through the finish line 😄 

Just to summarize a few requested changes:

- [ ] Rebase / merge in upstream master branch to get the latest changes and resolve merge conflicts.
- [ ] Remove irrelevant dependency and code changes, keep this PR single purposed - Next.js 15 and React 19 upgrade only
- [ ] Double check the latest versions on npm registry and make sure we are using the latest
- [ ] Please review all the framework features and make adjustments to the app as needed
- [ ] Please provide a description of every change for review
- [ ] Run linter

Afterwards, if you have time, 

- [ ] Please recommend future improvements that can be adopted for NextJS after the initial upgrade.
- [ ] Could you comment on any new features or changes nextjs and react 19 brings that we should adopt or could benefit from in the project? 

Please let me know, completely fine if you don't currently have the bandwidth to tackle this, many thanks!

2024-12-03 14:39 UTC, KemingHe commented
Hi @wei , I'm happy to continue and ultimately deliver this upgrade building on top of what @shubhamkhan have so far. Let me know how you'd like me to proceed after #405 . 

Best, K.H

2024-12-12 05:26 UTC, wei commented
> Hi @wei , I'm happy to continue and ultimately deliver this upgrade building on top of what @shubhamkhan have so far. Let me know how you'd like me to proceed after #405 .
> 
> Best, K.H

This is the last major remaining roadblock before new features can be worked on. @KemingHe Your help would be greatly appreciated if you've got time to help take this across the finish line. Feel free to make a new branch/PR as I also don't seem to have write permission on this one. 

@shubhamkhan Please let me know if you will have time to help with this before I close this PR due to inactivity. TY!

2024-12-12 13:31 UTC, shubhamkhan commented
Hi @wei and @KemingHe Thanks for continuing the PR.

2024-12-12 13:31 UTC, closed without merging