🥅 Feat: handle long svg data uri
wei/socialify pull request #440
Opened 2024-12-13 17:34 UTC by slusy

#### Reference Issues / PRs

closes #419

#### What does this implement/fix?

#### Any other comments?

2024-12-13 18:43 UTC, wei requested changes
@slusy thanks for your PR! Please see comments above. and any way you can add a playwright test - you can write in Codespaces by click on "Code" dropdown on the PR?

2024-12-13 18:43 UTC, wei commented on src/components/configuration/config.tsx
> +          errorMessage="URI is too long, please use an SVG image URL instead."
What do you think about removing isError and the new isSvgUriError altogether? 

Using `error={config.logo.length > 1600  ? 'XXXXX' : undefined}` to control both the error state and message in one prop?

2024-12-13 18:43 UTC, wei commented on src/components/configuration/inputWrapper.tsx
> +          <span className="label-text-alt text-red-400 italic">
No need for italic for now~

2024-12-14 06:26 UTC, slusy commented on src/components/configuration/config.tsx
> +          errorMessage="URI is too long, please use an SVG image URL instead."
Yes, this appears clean

2024-12-14 06:35 UTC, slusy commented
> @slusy thanks for your PR! Please see comments above. and any way you can add a playwright test - you can write in Codespaces by click on "Code" dropdown on the PR?

@wei should I use the same strategy for playwright like other tests, like taking screenshots and comparing?

2024-12-14 06:55 UTC, wei commented
Yes, screenshots for sure and please use your discretion to include additional tests as appropriate.

2024-12-14 17:46 UTC, wei requested changes

2024-12-14 17:46 UTC, wei commented on src/components/configuration/configuration.test.tsx
For unit tests around InputWrapper component, please create a test file `inputWrapper.test.tsx` .

2024-12-14 17:46 UTC, wei commented on src/components/configuration/configuration.test.tsx
> +        error="URI is too long, please use an SVG image URL instead."
It appears the error will be shown regardless of the value of invalidInput in this test. You can add tests of the input wrapper component itself in `inputWrapper.test.tsx` to see if label/plaecholder/error and everythign else is displayed correctly instead of testing for the long logo specifically. Same thing for line 38 below. 

If we'd like to test for handling of error display for long logo inputs in unit tests, we might have better luck creating a `<LogoInput />` component what wraps input wrapper.

2024-12-14 17:46 UTC, wei commented on src/components/configuration/config.tsx
>            handleChange={handleChange}
I just realized we still try to set the url in the address bar if it's long, should we add a maxlen prop here so it doesn't get too long?

2024-12-15 16:02 UTC, slusy commented on src/components/configuration/config.tsx
>            handleChange={handleChange}
We can trim the user input by using maxLength attribute, but isn't it better to show an error message?

```
if(key === 'logo' && value?.val?.length > 1600) {
        toast.error("URI is too long, please use an SVG image URL instead.")
        return
}
```

We can bypass the API request by performing the above in the `handleChange` function. The user will also receive information from the toast message, and the error message will not affect the rest of the UI. What are your thoughts?

2024-12-15 16:09 UTC, wei commented on src/components/configuration/config.tsx
>            handleChange={handleChange}
Thanks for the example! I’m open to this idea as long as the url isn’t changed.

2024-12-15 16:10 UTC, wei commented on src/components/configuration/config.tsx
>            handleChange={handleChange}
No need for the additional toast though, we still prefer the error message under the input the way you have it.

2024-12-15 16:57 UTC, slusy commented on src/components/configuration/config.tsx
>            handleChange={handleChange}
> No need for the additional toast though, we still prefer the error message under the input the way you have it.

Then I think it's better to go with the previous method. Also we can utilize maxLength to reduce the length,

```
error={
    config?.logo?.length === 1601 ? 'URI is too long, please use an SVG image URL instead.' : undefined
}
maxlen={1601}
```

what do you think?

2024-12-15 17:00 UTC, wei commented on src/components/configuration/config.tsx
>            handleChange={handleChange}
Sounds great!

2024-12-17 06:40 UTC, wei approved these changes

2024-12-17 06:41 UTC, merged

2024-12-17 06:46 UTC, wei commented
@slusy made some final edits and just merged 🥳  https://github.com/wei/socialify/blob/811ccd2d21b2df3697755326a0ca82c207c84b87/CHANGELOG.md?plain=1#L3-L9