♻️ Full front+backend migration from page router to app router
wei/socialify pull request #450
Opened 2024-12-16 01:23 UTC by KemingHe

## Part 1/2 to Migrate to NextJS 15/React 19

- [x] All existing Playwright behavior testing passing.
- [x] Added new Playwright screenshot tests to all 4 image endpoints.
- [x] Updated unit tests to reflect the new architectural changes.

Thank you @wei for your tremendous support; I look forward to replying to your review.

2024-12-16 01:24 UTC, KemingHe commented
Ref: step 1/2 to resolve #373 .

2024-12-16 01:41 UTC, wei reviewed
This is wonderful 💯! I see so many great improvements. 

I left a few questions above please review and lmk your thoughts. 

I'll conduct a more thorough review when I'm on my computer tomorrow. 🙌

2024-12-16 01:41 UTC, wei commented on src/hooks/useRouteResources.ts
> +export function UseRouteResources(): RouteResources {
Let's rename to useRouteResources to be consistent with react hook naming convention

2024-12-16 01:41 UTC, wei commented on src/components/configuration/config.tsx
> +  }, [searchParamsString])
Excellent refactor!

2024-12-16 01:41 UTC, wei commented on app/layout.tsx
> +        <meta name="viewport" content="minimal-ui" />
does the export viewport overwrite this meta tag?

2024-12-16 01:41 UTC, wei commented on app/api/image/route.ts
I believe we are expected to always returning svg for this endpoint, please correct me if I'm wrong.

2024-12-16 02:30 UTC, KemingHe commented on app/layout.tsx
> +        <meta name="viewport" content="minimal-ui" />
Actually no, the NextJS `Viewport` and `Metadata` export merely **appends** the corresponding elements to the `<head>`. Can confirm my inspecting my browser.

2024-12-16 02:35 UTC, KemingHe commented on src/hooks/useRouteResources.ts
> +export function UseRouteResources(): RouteResources {
Resolved in latest commit. Thank you for point it out.

2024-12-16 04:10 UTC, wei commented on app/layout.tsx
> +        <meta name="viewport" content="minimal-ui" />
Looks like we can remove minimal-ui as it’s been deprecated a while~

2024-12-17 05:05 UTC, wei commented on package.json
> +    "react-dom": "19.0.0",
Should we prepend with `^` to match future versions in the major release?

2024-12-17 05:05 UTC, wei commented on package.json
> +  }
What's this override for?

2024-12-17 05:06 UTC, wei commented on tsconfig.json
Did something in biome change to trigger this update?

2024-12-17 17:25 UTC, KemingHe commented on package.json
> +    "react-dom": "19.0.0",
I agree, adding in next commit.

2024-12-17 17:27 UTC, KemingHe commented on package.json
> +  }
This is the raw result from the codemod. I also agree that this is odd. Currently testing what happens if I remove it.

2024-12-17 17:41 UTC, KemingHe commented on package.json
> +  }
All tests (unit and behavior) passing after removal of the override part. Determined safe removal for the time being.

No mentioning of this change found on https://nextjs.org/blob/next-15 nor the official upgrade guide.

2024-12-17 17:45 UTC, KemingHe commented on tsconfig.json
Biome is not part of the update codemod. Can confirm biome also did not edit that portion of `package.json` as re-running the linter/formatter after deletion does not get it back.

2024-12-17 17:52 UTC, KemingHe commented
`server-only` is a react (not next) marker that enforces usage of the module that imports it to run on server-side. It's widely used to explicitly protect code involving server-side secrets.

I'll let you ultimately decide whether to keep it. It's extremely light-weight w/ no versioning/upgrade needed.

2024-12-17 23:56 UTC, wei commented
👍 server-only is definitely a good DX and build time improvement. https://nextjs.org/docs/app/building-your-application/rendering/composition-patterns#keeping-server-only-code-out-of-the-client-environment

2024-12-17 23:58 UTC, wei commented on app/api/graphql/route.ts
> +    duplex: 'half',
Do you have any docs on why this is now needed?

2024-12-18 00:10 UTC, wei requested changes
Could you apply these two changes for Next15 upgrade?
* https://nextjs.org/docs/app/api-reference/file-conventions/metadata/manifest
* https://nextjs.org/docs/app/api-reference/file-conventions/metadata/app-icons

2024-12-18 00:39 UTC, KemingHe commented on app/api/graphql/route.ts
> +    duplex: 'half',
Yes, this is actually an official nodejs fetch api "issue": https://github.com/nodejs/node/issues/46221

(Also encountered by graphql-yoga folks: https://github.com/dotansimha/graphql-yoga/discussions/3175)

More straightforwardly, you can try to remove it and read the error message about needing it. I personally am not too well-versed on the root cause yet, even after researching the error.

2024-12-18 00:41 UTC, wei commented on app/api/graphql/route.ts
> +    duplex: 'half',
Thanks for the link! Did this only become a problem after migrating to app router?

2024-12-18 16:09 UTC, KemingHe commented on app/api/graphql/route.ts
> +    duplex: 'half',
It appears so @wei , my speculation is that it's caused by the now explicit use of React server component as a POST endpoint. In app router, we didn't even enforce 'server-only'. 

Another possibility is by some inner working of the app router, not directly related to React. Both (and maybe more) are just my best guesses.

2024-12-18 18:05 UTC, KemingHe commented
Hi @wei , I used [`https://realfavicongenerator.net/`](https://realfavicongenerator.net/) to double-confirm my favicon and manifest updates are good. I did **not** re-generate/format any of the files, only copy/rename.

P.S. It's a known issue that their site's `favicon.ico` check is bugged recently, everything else works fine, so no worries.

2024-12-18 18:12 UTC, KemingHe commented
I also found this unexpected behavior where the import breaks for the `wasm` module as soon as I touched the `public` dir. The fix is to revert (only) them to relative imports. 

I suspect this is related to how next caches/imports? `public` dir and how the behavior changed once `favicon.ico` and `manifest.json` got moved out.

2024-12-18 22:39 UTC, wei commented
@KemingHe  That all sounds and looks great! I was previewing the feature branch and noticed the selected font is not loaded for the preview. Everything else is working well. Could you help confirm the font is loaded correctly?

<img width="1194" alt="image" src="https://github.com/user-attachments/assets/8f2f80ed-d0a4-4d89-a1b6-264e1e5d5ae4" />

2024-12-19 00:54 UTC, KemingHe commented
Hi @wei , assuming you are referring to the latest [`https://deploy-preview-450--github-socialify.netlify.app/`](https://deploy-preview-450--github-socialify.netlify.app/) preview, here's what I found:

- All image urls are working (with custom fonts).
- Only the Inter/Non-inter font change is working on preview config page (page refresh doesn't fix it).

I have a few ideas on the root cause, but before we get into that, what if you try to create a branch off the current working `master` and deploy a preview without any changes to see if the issues are also present and consistent?

If so I argue that we are actually good to merge to `master`. Otherwise we can keep investigating. What do you think?

2024-12-19 01:01 UTC, wei commented
@KemingHe good point!

I just checked the master branch deployment, permalink: https://67611dae31fa580008b7c232--github-socialify.netlify.app and confirmed fonts are working correctly.

2024-12-19 01:36 UTC, wei commented
I believe the permalink act the same as the pull request preview deployments.

---

Image APIs add fonts within the svg so it's slightly different:

https://github.com/wei/socialify/blob/811ccd2d21b2df3697755326a0ca82c207c84b87/common/renderSVG.tsx#L25

Whereas the preview page loads font like this:

https://github.com/wei/socialify/blob/811ccd2d21b2df3697755326a0ca82c207c84b87/src/components/preview/preview.tsx#L129-L140

I noticed in master, these two font stylesheet links are added to head, but not in the pull request preview domain:
<img width="971" alt="image" src="https://github.com/user-attachments/assets/f408b705-fb83-45d8-9cde-5e2efbbbf045" />

I see no changes around these lines here so it might be related to how <Head> and link headers are handled.

RE: font fallback is not used as defined in root layout as the font family was overwritten without a fallback:
<img width="336" alt="image" src="https://github.com/user-attachments/assets/ed1b77de-7ec5-4686-b7db-b3d1134bed4e" />

2024-12-19 01:43 UTC, KemingHe commented
**YES** using vanilla `<head>` solves the issue, even in preview. Committing the fix right now.

2024-12-19 01:44 UTC, wei commented
We can't have two `<head>`s in an html, the nextjs `<Head>` is a helper component acting a portal to move whatever is in there to the actual html's `<head>`.

2024-12-19 01:45 UTC, KemingHe commented
I propose we (I) modify the current Playwright `simpleUserStory.spect.ts` to cover this case. This will require a snapshot update. What do you think?

2024-12-19 01:50 UTC, wei commented
Confirmed `next/head` does not work with app router per https://github.com/vercel/next.js/discussions/53529#discussioncomment-6628991

I'm working on an alternative.

2024-12-19 02:27 UTC, KemingHe commented
@wei , my latest commit is a (like you said) "bad practice" fix, as it uses the html `<head>` in `preview.tsx`. Still, please use the updated user story snapshots to confirm your better solution. Excited for the great news.

2024-12-19 03:05 UTC, wei approved these changes
@KemingHe ✅ Approved!! I'm so excited.

2024-12-19 03:05 UTC, merged